## Упражнения по библиотеке Numpy

In [3]:
import numpy as np
import random

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [4]:
rng = tuple(range(4, 8))
array = np.random.randint(0, 15, (2, 10))
print(array)
for item in np.nditer(array, op_flags = ['readwrite']):
    if item in rng:
        item -= item*2
array



[[ 0  7  0 14 11  2  7  9 11 12]
 [ 1  1 10 14 12 14  6  1 12 12]]


array([[ 0, -7,  0, 14, 11,  2, -7,  9, 11, 12],
       [ 1,  1, 10, 14, 12, 14, -6,  1, 12, 12]])

**2.** Заменить максимальный элемент случайного массива на 0

In [5]:
rnd_array = np.random.randint(0, 1000, 15)
print(rnd_array)
rnd_array[np.argmax(rnd_array)] = 0
print(rnd_array)







[482 487 253 458  66 727 579 320 636 847 699 604 379 446 250]
[482 487 253 458  66 727 579 320 636   0 699 604 379 446 250]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [7]:
a = np.random.randint(0, 3, (5, 5))
b = np.random.randint(0, 1000, (5, 5))
np.dot(a, b)

array([[2629, 2212, 1423, 2531, 1240],
       [3814, 4358, 2933, 3389, 2761],
       [5281, 4979, 4043, 4000, 3912],
       [3919, 4059, 2841, 3082, 2230],
       [5436, 4456, 3097, 3223, 3645]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [8]:
A = np.random.randint(0, 10, (8, 3))
B = np.random.randint(0, 10, (2, 2))
print(A)
print('--------')
print(B)
print('--------')
I = np.isin(A, B)
print(I)
print('--------')
i = 0
for item in A:
    if np.array_equal(np.array([False, False, False]), I[i]):
        i += 1
        continue
    print(item)
    i += 1

[[5 0 5]
 [1 8 5]
 [0 1 4]
 [9 6 7]
 [7 5 0]
 [6 8 9]
 [6 3 5]
 [5 6 2]]
--------
[[0 9]
 [8 8]]
--------
[[False  True False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [False  True  True]
 [False False False]
 [False False False]]
--------
[5 0 5]
[1 8 5]
[0 1 4]
[9 6 7]
[7 5 0]
[6 8 9]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [9]:
Z = np.random.randint(0,2,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print('--------------------')
print(U)


[[1 0 1]
 [1 1 1]
 [0 1 1]
 [0 0 0]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [0 1 1]]
--------------------
[[1 0 1]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [1 0 1]
 [0 1 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [10]:
A = np.random.randint(0, 3, (8, 2))
print(A)
np.unique(A, axis=0)

[[0 0]
 [1 2]
 [0 2]
 [0 0]
 [2 0]
 [0 0]
 [2 2]
 [1 2]]


array([[0, 0],
       [0, 2],
       [1, 2],
       [2, 0],
       [2, 2]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [11]:
# ---------------------------Numpy
A = np.random.randint(0, 14, (8, 5))
print(A)
print(np.diagonal(A))
print('----------------------')
# ---------------------------Python
a = [[random.randint(0, 5) for i in range(3)] for i in range(5)]
print(a)
print([a[i][i] for i in range(len(a[0]))])






[[ 6  8  1  4  7]
 [11  0  3 10 11]
 [11  1  5 13  4]
 [ 3  3  8  1 10]
 [10  4 11  5  0]
 [ 0 13  8 13 11]
 [ 9 13  8  0  9]
 [ 8 12  2  0  3]]
[6 0 5 1 0]
----------------------
[[5, 2, 5], [5, 2, 2], [0, 3, 0], [3, 4, 3], [5, 0, 4]]
[5, 2, 0]


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [12]:
# ---------------------------Python
x = [14, 22, 22, 4, 333, 15, 932]
y = [14, 22, 22, 4, 15, 932, 333]
print(sorted(x)==sorted(y))

# ---------------------------Numpy
x = np.array([14, 22, 22, 4])
y = np.array([4, 22, 14, 22])
print(np.array_equal(np.sort(x), np.sort(y)))



True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [147]:
# ---------------------------Python
listt = [random.randint(0, 15) for i in range(25)]
after_zero = [listt[i] for i in range(1, len(listt)) if not listt[i-1]]
try:
    maxx = max(after_zero)
    print(f'MAX = {maxx}')
except ValueError as _e:
    print(f'EXEPTION: {_e}')
    print(listt)
    print(after_zero)
print('-----------------')
# ---------------------------Numpy
arr = np.random.randint(0,5,10)
all_zeroes = arr == 0
try:
    print(f'MAX = {arr[1:][all_zeroes[:-1]].max()}')
except ValueError as _e:
    print(f'EXEPTION: {_e}')
    print(f'No zeroes {arr}')



MAX = 3
-----------------
EXEPTION: zero-size array to reduction operation maximum which has no identity
No zeroes inside array [3 4 2 2 4 3 4 1 3 3]


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [361]:
# ---------------------------Python
import itertools

listt = [1, 1, 1, 3, 3, 3, 23, 23, 1, 8, 42, 42]
result1 = []
result2 = []

def grouper(listt):
    for digit, same in itertools.groupby(listt):
            count = sum(1 for elem in same)
            result1.append(digit)
            result2.append(count)
    return tuple(result1), tuple(result2)

A, B = grouper(listt)
print(A, B)
#---------------------------Numpy
print('------------------------NumPY')
listt = [1, 666, 1, 1, 1, 3, 3, 3, 23, 23, 1, 8, 42, 42, 555, 555, 555, 1, 777]

arr = np.array(listt)
arr = np.insert(arr, 0, arr[0]+1, axis=0)
arr = np.append(arr, arr[-1]+1)

compare = arr[1:] == arr[:-1]
print(compare)
B = np.concatenate([compare, [~compare[-1]]])
print('------------------------RESULT-1')
print(arr[1:-1][~B[1:-1]])
O = np.where(B == 0)[0]
print('------------------------RESULT-2')
print(np.diff(O))

print('------------------------Решение-2(с)')
listt = [1, 666, 1, 1, 1, 3, 3, 3, 23, 23, 1, 8, 42, 42, 555, 555, 555, 1, 777]

arr = np.array(listt)
b = arr
y = b[1:] != b[:-1]   
i = np.append(np.where(y), len(b) - 1)
z = np.diff(np.append(-1, i))  
print(z, b[i])






(1, 3, 23, 1, 8, 42) (3, 3, 2, 1, 1, 2)
------------------------NumPY
[False False False  True  True False  True  True False  True False False
 False  True False  True  True False False False]
------------------------RESULT-1
[  1 666   1   3  23   1   8  42 555   1 777]
------------------------RESULT-2
[1 1 3 3 2 1 1 2 3 1 1]
------------------------Решение-2(с)
[1 1 3 3 2 1 1 2 3 1 1] [  1 666   1   3  23   1   8  42 555   1 777]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [296]:
from scipy.spatial.distance import cdist
import time
from functools import reduce
from itertools import starmap
from operator import mul, sub, pow

# ---------------------------Python
coord1 = [1, 2, 3], [1, 22, 3], [3, 3, 3], [3, 3, 3]
coord2 = [5, 6, 7], [12, 12, 12], [1, 2, 3], [3, 3, 3]


def matrixsub_and_sqrt(a, b):
    matrix = []
    for i, row in enumerate(a):
        matrix.append(zip(row, b[i]))

    for row in matrix:
        yield [*(list((starmap(lambda x, y: (x-y)**0.5, row))))]
    

def matrixmul(a, b):
    for row in a:
        yield [sum(starmap(mul, zip(row, row2)))*2 for row2 in b]

        
def dist_pairwise(a, b):
    if len(a)==len(b):
        result = []
        for item1 in a:
            row = []
            squared_sum1 = reduce(lambda x, y: x + y**2, item1, 0)
            for item2 in b:
                squared_sum2 = reduce(lambda x, y: x + y**2, item2, 0)
                row.append(squared_sum1 + squared_sum2)
            result.append(row)
        return result


print('------------------------------------Python')
start_time = time.time()
A = dist_pairwise(coord1, coord2)
B = list(matrixmul(coord1, coord2))
C = matrixsub_and_sqrt(A, B)
print("Python--- %s seconds ---" % (time.time() - start_time))
print(f'Result = {result}')

# ---------------------------Numpy
print('------------------------------------Numpy')
XA = np.array([*coord1])
XB = np.array([*coord2])

def dist_pairwise(a, b):
    P = np.add.outer(np.sum(a**2, axis=1), np.sum(b**2, axis=1))
    N = np.dot(a, b.T)
    return np.sqrt(P - 2*N)

start_time = time.time()
result = dist_pairwise(XA, XB)
print("Numpy--- %s seconds ---" % (time.time() - start_time))
print(f'Result = {result}')


# ---------------------------Skipy
print('------------------------------------Skipy')
start_time = time.time()

Y = cdist(XA, XB, 'euclidean')
print("Skipy--- %s seconds ---" % (time.time() - start_time))
print(f'Result = {Y}')

------------------------------------Python
Python--- 0.00043582916259765625 seconds ---
Result = [[ 6.92820323 17.3781472   0.          2.23606798]
 [16.97056275 17.3781472  20.         19.10497317]
 [ 5.38516481 15.58845727  2.23606798  0.        ]
 [ 5.38516481 15.58845727  2.23606798  0.        ]]
------------------------------------Numpy
Numpy--- 0.0003490447998046875 seconds ---
Result = [[ 6.92820323 17.3781472   0.          2.23606798]
 [16.97056275 17.3781472  20.         19.10497317]
 [ 5.38516481 15.58845727  2.23606798  0.        ]
 [ 5.38516481 15.58845727  2.23606798  0.        ]]
------------------------------------Skipy
Skipy--- 0.0003414154052734375 seconds ---
Result = [[ 6.92820323 17.3781472   0.          2.23606798]
 [16.97056275 17.3781472  20.         19.10497317]
 [ 5.38516481 15.58845727  2.23606798  0.        ]
 [ 5.38516481 15.58845727  2.23606798  0.        ]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [299]:
import numpy as np
import pandas as pd


1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [302]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [395]:
average_calories = calorie_stats.mean()
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [396]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [333]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [383]:
for i in range(1, 101):
    if np.percentile(calorie_stats, i) > 60:
        nth_percentile = i
        print(f'Min percentil > 60 cal = {nth_percentile}%')
        print(f'{100-nth_percentile}% of concurents have more colories than CrunchieMunchies have')
        break

Min percentil > 60 cal = 4%
96% of concurents have more colories than CrunchieMunchies have


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [397]:
more = np.sum(calorie_stats > 60)
more_calories = more*100/calorie_stats.size
print(more_calories)

96.1038961038961



7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [393]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.